# This file contains Kubernetes YAML files for the most important prow
# components. Don't edit resources in this file. Instead, pull them out into
# their own files.
---
apiVersion: v1
kind: Namespace
metadata:
  name: prow
---
apiVersion: v1
kind: Secret
metadata:
  namespace: prow
  name: github-token
stringData:
  cert:  <github-app-private-key>
  appid: "<github-app-id>"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: prow
  name: hmac-token
stringData:
  # Generate via `openssl rand -hex 20`. This is the secret used in the GitHub webhook configuration
  hmac: "<hmac-token>"
